[nginx]
nginx-proxy ansible_host=192.0.2.10 # Replace with output.nginx_public_ip

[frontend]
frontend-srv ansible_host=10.0.2.20 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q app-runner@192.0.2.10"'

[backend]
backend-srv  ansible_host=10.0.2.30 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q app-runner@192.0.2.10"'

[worker]
worker-srv   ansible_host=10.0.2.40 ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q app-runner@192.0.2.10"'

[app_servers:children]
frontend
backend
worker